# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'passpie-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for passpie-ios
  pod 'Alamofire'
  pod 'ObjectivePGP'
  pod 'Yaml'
end
